[profile.default]
libs = ['lib']
out = 'out'
src = 'src'

optimizer = true
optimizer_runs = 200
solc_version = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
fivenet = {key = "your API key", chain = 150, url="https://fivenet.evm.sixscan.io/api"}